### ISSUE TITLE
Class diagrams & Role playing

### ISSUE THREAD

**Issue by santanca** [MadeehaKhan/Pillbox#5]
Create class diagrams and do some "role playing"

**Comment by carlossantana3279** [comment]
https://docs.google.com/spreadsheets/d/1cY_bbRlR7qJY17t9YbB5kE6rrmB1odaG7GM8ZRMcL2s/edit#gid=0

Entity Classes Created during meeting

**Comment by carlossantana3279** [comment]
All the other classes still need to be done
